apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-linkedin
  labels:
    app: mcp-linkedin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-linkedin
  template:
    metadata:
      labels:
        app: mcp-linkedin
    spec:
      containers:
        - name: mcp-linkedin
          image: quay.io/vajain/mcp-linkedin:4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always